# Informations du site 
site_name: TSI_2021-2022
site_description: Numérique et Sciences Informatique en classe de terminale au lycée Notre Dame du Mur de MORLAIX.
site_author: "Eric MADEC" 
copyright: Document partagé par <a href="https://github.com/ericECmorlaix" target="_blank">Eric MADEC</a> &copy; 2021 sous licence <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr" target="_blank">CC BY-NC-SA 4.0</a>
site_url: https://ericecmorlaix.github.io/TSI_2021-2022/

# Dépot du projet 
repo_name: 'TSI_2021-2022' 
repo_url: https://github.com/ericECmorlaix/TSI_2021-2022 # Ajoute l'icone et le lien vers le dépot GitHub en haut à droite
edit_uri: tree/main/docs/


# Structure des dossiers :
docs_dir: docs

# Menu de navigation
nav: 
    - Cahier de texte : index.md
    - Présentation : presentation.md
    - Les notebook jupyter :
      - Découverte : decouverte-notebook.ipynb
      - Markdown : MarkDown-Le_BN_pour_rapporter.ipynb
      - HTML : HTML-Le_BN_pour_multimedier.ipynb
      - LaTeX : LaTeX-Le_BN_pour_formuler.ipynb
      - Calcul : Arithmetique-Le_BN_pour_calculer.ipynb
    - Projets :
      - nsisium : nsisium.md
      - course en cours : cec.md
    - AM Béquille de moto : Actions_Mecaniques-Bequille_De_Moto.ipynb
    - Modelisation_3D.md
    - Ressources : ressources.md

# Définition du thème https://squidfunk.github.io/mkdocs-material/creating-your-site/
theme:
    name: material
    custom_dir: overrides
    font: false  # RGPD ; pas de fonte Google
    language: fr # français
    logo: images/LogoIO.png 
    favicon: images/LogoIO-red.png

    palette: # Palettes de couleurs jour/nuit, cf : https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
      - scheme: default # nom du thème clair
        primary: red # couleur primaire des titres, des liens, ..., à prendre dans la liste
        accent: brown # couleur d'accentuation au survol des boutons, desliens, ..., à prendre dans la liste
        toggle: # définition du bouton pour switcher de palette
          icon: material/weather-sunny # apparence
          name: Basculer en mode sombre # message
      - scheme: slate # nom du thème sombre
        primary: brown
        accent: red
        toggle:
          icon: material/weather-night
          name: Basculer en mode clair

    features:
        - navigation.instant
        - navigation.tabs
        - navigation.expand
        - navigation.top
        - toc.integrate
        - header.autohide


### Configuration des extensions MarkDown :        
markdown_extensions: # https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
    # extensions de la bibliothèque markdown standard
    - abbr                          # Infobulles sur abbréviations 
    - meta                          # Métadonnées
    - def_list                      # Listes de définition.
    - attr_list                     # Sélecteurs CSS et attributs HTML personnalisés
    - md_in_html                    # Pour écrire en MarkDown dans des balises HTML https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Boite d'avertissements  !!! info "ma remarque"
    - toc:                          # Configuration de la table des matières générée automatiquement à partir des titres du niveau 2
        permalink: "&num;"          # Ajoute un symbole lien hypertexte vers l'ancre du titre #le-titre 
        toc_depth: 4                # Limite de la profondeur d'inclusion des titres dans la table des matières
    # extensions de python-markdown https://facelessuser.github.io/pymdown-extensions/
    - pymdownx.details              # plier/déplier les avertissements.
    - pymdownx.caret                # texte ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # texte ==surligné==.
    - pymdownx.tilde                # texte ~~barré~~ ou en ~indice~.
    - pymdownx.critic               # Pour du marquage et commentaires de révision de texte
    - pymdownx.highlight            # Coloration syntaxique du code
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    true    #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed:              # Onglets coulissants.  === "Onglet"
        alternate_style: true       # Ajout depuis la version 8
    - pymdownx.superfences          # Imbrication de blocs.
    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:               # Émojis  :boom:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:          # Formules en LaTeX 
        generic: true
        smart_dollar: false
    
  

plugins:
  - search # Inclure une barre de recherche
  - mkdocs-jupyter: # Convertir les fichiers .ipynb et .py en pages du site https://github.com/danielfrg/mkdocs-jupyter
      kernel_name: python3
      execute: False
      include_source: True


extra:
  social: 
    - icon: fontawesome/solid/paper-plane
      link: mailto:eric.madec@ecmorlaix.fr
      name: Pour toute question, suggestion ou commentaire, écrire à l'auteur
    - icon: fontawesome/brands/github
      link: https://github.com/ericECmorlaix/TSI_2021-2022
      name: dépôt github
    - icon: fontawesome/solid/university
      link: https://www.ecmorlaix.fr/nos-etablissements/lycee-notre-dame-du-mur/
      name: Lycée Notre Dame du Mur


extra_javascript:
  - javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css